#!/usr/bin/env python

""" Generate script for individual task.
"""
import os

from task import tasks
from util import FilePath

here = FilePath(os.path.dirname(os.path.abspath(__file__)))

def content_template(task_name):
    return '''#!/usr/bin/env python
""" Generated by source/genscript.py. Don't modify!
"""
import sys
sys.path.insert(0, '%s')
from task import tasks
tasks['%s']()
''' % (here, task_name)

def main():
    for name in tasks:
        path = here / '..' / '%s.gen.py' % name
        with open(path, 'wb') as f:
            f.write(content_template(name))
            print('Generated %s' % path)
        os.chmod(path, 0755)

if __name__ == '__main__':
    main()

