#!/usr/bin/env python
""" Generated by source/genscript.py. Don't modify!
"""
import sys
sys.path.insert(0, '/home/overmind/ref/postile-dev/frontend/build-script/source')
from task import tasks
tasks['fetch_tools']()
